name: 'ci'
on:
    pull_request:
        branches:
            - master

jobs:
    test:
        name: 'Test'
        runs-on: 'ubuntu-latest'
        if: "!contains(github.event.head_commit.message,'#skip-ci')"

        strategy:
            matrix:
                node-version: [10.x, 12.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
            - name: setup yarn
              run: yarn install
            - run: yarn typecheck
            - run: yarn lint
            - run: yarn test
              env:
                  CI: true
                  YARN_REGISTRY: https://registry.npmjs.org/
