name: 'deploy'
on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: 'Deploy'
        runs-on: 'ubuntu-latest'
        if: "!contains(github.event.head_commit.message,'#no-deploy')"

        strategy:
            matrix:
                node-version: [10.x, 12.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
            - run: yarn install
            - run: yarn deploy
              env:
                  CI: true
