name: 'deploy'
on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: 'Deploy'
        runs-on: 'ubuntu-latest'

        if: "!contains(github.event.head_commit.message,'#no-deploy')"

        steps:
            - uses: actions/checkout@v2
            - uses: oleksiyrudenko/gha-git-credentials@v1
              with:
                  token: '${{ secrets.GITHUB_TOKEN }}'
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn install
            - run: yarn deploy
              env:
                  CI: true
